name: packages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16          

      - name: Install dependencies and build
        run: |
          for dir in packages/*; do
            if [ -f "$dir/package.json" ]; then
              echo "Building $dir"
              cd "$dir"
              npm install
              npm run lib 
              cd ..
            fi
          done
