name: root-ci

on:
  push:
    branches:
      - main
    paths:
      - '!apps/**'
      - '!packages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16          

      - name: Install dependencies
        run: npm install     
